#apiVersion: apps/v1beta1
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
#apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: learn-spring-kotlin-app-prod
  labels:
    app: learn-spring-kotlin-app-prod
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 30
  selector:
    matchLabels:
      app: learn-spring-kotlin-app-prod

  template:
    metadata:
      labels:
        app: learn-spring-kotlin-app-prod
    spec:
      containers:
      - name: learn-spring-kotlin-app-prod
        image: docker.io/bastman77/learn-spring-kotlin:2017-11-30T13.41.37Z
        command: ["java"]
        args: ["-jar", "-Dspring.profiles.active=prod", "-Xms32m", "-Xmx256m", "/opt/learn-spring-kotlin/app.jar"]

        resources:
          requests:
            memory: "512M"
            cpu: 0.4
          limits:
            memory: "1.0G"
            cpu: 0.8
        ports:
        - containerPort: 8080

