version: '3'
services:
  learn-spring-kotlin-app:
    image: "local/${SERVICE_NAME}:${SERVICE_VERSION}"
    ports:
      - "8080:8080"
    command: ["java","-jar","-Dspring.profiles.active=local", "/opt/${SERVICE_NAME}/app.jar"]
    #restart: always

